[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.26"

[features]
resolution = true
skip-lint = false

[programs.localnet]
shotgun_radium = "CHbnhtNeCb6YmDkesWCbh2swC35HqkGPhC7q17CzMuak"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "tests/keys/pFCBP4bhqdSsrWUVTgqhPsLrfEdChBK17vgFM7TxjxQ.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000
shutdown_wait = 2000

[test.validator]
url = "https://api.mainnet-beta.solana.com"
ticks_per_slot = 16  # normally there are 64 ticks

# *** Programs ***

## Raydium AMM
[[test.genesis]]
address = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
program = "tests/fixtures/mainnet/raydium/programs/raydium_amm.so"


# *** Accounts ***

## Raydium for SOL/USDC pool

### pool id
[[test.validator.clone]]
address = "58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2"

### LP token mint
[[test.validator.clone]]
address = "8HoQnePLqPj4M7PUDzfw8e3Ymdwgc7NLGnaTUapubyvu"

### authority
[[test.validator.clone]]
address = "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1"

### open orders
[[test.validator.clone]]
address = "HRk9CMrpq7Jn9sh7mzxE8CChHG8dneX9p475QKz4Fsfc"

### target orders
[[test.validator.clone]]
address = "CZza3Ej4Mc58MnxWA385itCC9jCo3L1D7zc3LKy1bZMR"

### base vault
[[test.validator.clone]]
address = "DQyrAcCrDXQ7NeoqGgDCZwBvWDcYmFCjSb9JtteuvPpz"

### quote vault
[[test.validator.clone]]
address = "HLmqeL62xR1QoZ1HKKbXRrdN1p3phKpxRMb2VVopvBBz"

### market ID
[[test.validator.clone]]
address = "9wFFyRfZBsuAha4YcuxcXLKwMxJR43S7fPfQLusDBzvT"

### market authority
[[test.validator.clone]]
address = "F8Vyqk3unwxkXukZFQeYyGmFfTG3CAX4v24iyrjEYBJV"

### market base vault
[[test.validator.clone]]
address = "36c6YqAwyGKQG66XEp2dJc5JqjaBNv7sVghEtJv4c7u6"

### market quote vault
[[test.validator.clone]]
address = "8CFo8bL8mZQK8abbFyypFMwEDd8tVJjHTTojMLgQTUSZ"

### market bids
[[test.validator.clone]]
address = "14ivtgssEBoBjuZJtSAPKYgpUK7DmnSwuPMqJoVTSgKJ"

### market asks
[[test.validator.clone]]
address = "CEQdAFKdycHugujQg9k2wbmxjcpdYZyVLfV9WerTnafJ"

### market event queue
[[test.validator.clone]]
address = "5KKsLVU6TcbVDK4BS6K1DGDxnh4Q9xjYJ8XaDCG5t8ht"

## USDC

### Mint -- USDC
[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "tests/fixtures/mainnet/usdc_mint.json"

### Base wallet (from anchor provider, this is how we get usdc on this account) Token Account -- USDC
[[test.validator.account]]
address = "4tKtuvtQ4TzkkrkESnRpbfSXCEZPkZe3eL5tCFUdpxtf"
filename = "tests/fixtures/mainnet/usdc_base_wallet_token.json"
